include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - 'lib/**/*.pb*.dart'

linter:
  rules:
    # TODO: Remove once docs are implemented.
    public_member_api_docs: false
    library_private_types_in_public_api: false
    avoid_print: false
