name: esp_provisioning_softap_example
description: Demonstrates how to use the esp_provisioning_softap plugin.

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  esp_provisioning_softap:
    path: ../
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_spinkit: ^5.2.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
